spring:
  application:
    name: training-fullstack
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  private-key: file:./keys/private.pem
  public-key: file:./keys/public.pem
  expiration-ms: 3600000

springdoc:
  swagger-ui:
    persist-authorization: true
    doc-expansion: none
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
